In [11]:
import numpy as np
v=np.array([0,1,2,3,4,5,6,7,8,9])
print(v)
print('dimension of v is', v.ndim)

[0 1 2 3 4 5 6 7 8 9]
('dimension of v is', 1)


In [18]:
odd=v[1::2]
odd

array([1, 3, 5, 7, 9])

In [65]:
backward=v[::-1]
print(backward)

[9 8 7 6 5 4 3 2 1 0]
