In [1]:
import numpy as np
x = np.array(42)
print(np.ndim(x))
print(x)
print(np.shape(x))

0
42
()


In [3]:
a=np.array([1,2,3,4,5,6,7])
print(type(a))
print(np.ndim(a))
np.shape(a)

<type 'numpy.ndarray'>
1


(7,)

In [40]:
b=np.array([ [1,2,3],
            [4,5,6] ])
print(np.ndim(b))
print('shape before modification is',np.shape(b))
print(b)
print('after reshaping')
b.shape=(3,2)
print(b)
print('shape after modification is',np.shape(b))

2
('shape before modification is', (2, 3))
[[1 2 3]
 [4 5 6]]
after reshaping
[[1 2]
 [3 4]
 [5 6]]
('shape after modification is', (3, 2))


In [28]:
c=[ [[1,2],[3,4]],
    [[5,6],[7,8]] ]
print(np.ndim(c))
np.shape(c)

3


(2, 2, 2)

In [41]:
change_array = np.array([1,2,3,4,5,6])
change_array.shape = (3, 2)
print change_array      

[[1 2]
 [3 4]
 [5 6]]


In [44]:
o = np.array([1,2,3,4,5])
print(o[0])
print(o[-1])

1
5


In [49]:
c=[ [[1,2],[3,4]],
    [[5,6],[7,8]] ]
print(c[0][1])

[3, 4]


In [67]:
s = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(s[:])
print(s[1:5])
print(s[4:8])
print(s[-2])
print(s[2:-1])
print(s[:3])
print(s[8:])
print(s[len(s)/2])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]
[4 5 6 7]
8
[2 3 4 5 6 7 8]
[0 1 2]
[8 9]
5


In [101]:
t = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])

print(np.ndim(t))
print(np.shape(t))
print(t[2,2:])
val=t[:,2]
print(val)
# displaying column result verically
for i in val:
    print(i)

2
(5, 5)
[33 34 35]
[13 23 33 43 53]
13
23
33
43
53


In [94]:
l = [[1,2,3],[4,5,6],[7,8,9]]
map(list, zip(*l))

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [93]:
np.array(l).T.tolist()

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [111]:
p = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])
g=p[:,3:4]
print(g)
# OR
print(p[:,3])
# OR
for i in g:
    print(i)


[[14]
 [24]
 [34]
 [44]
 [54]]
[14 24 34 44 54]
[14]
[24]
[34]
[44]
[54]


In [10]:
a = np.arange(6)
print(type(a))
print(a.dtype)
a.shape=(3,2)
b=a.reshape(2,3)
b

<type 'numpy.ndarray'>
int32


array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
x=np.array([1,2,3,4])
a=np.ones_like(x)
print(a)
s=np.ones(x)
print(s)
t=np.array([[4,5,6],[1,2,3]])
b=np.zeros_like(t)
print(b)

[1 1 1 1]
[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]
[[0 0 0]
 [0 0 0]]


In [12]:
import numpy as np
x=np.array([[1,2,34,5],[54,43,5,6]],order='K')
y=x.copy()
y[0][0]=0
print(x)
print(y)

[[ 1  2 34  5]
 [54 43  5  6]]
[[ 0  2 34  5]
 [54 43  5  6]]


In [14]:
import numpy as np
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
np.eye(4,3,k=-1,dtype=int)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [27]:
np.eye(3,k=1,dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])